apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: video-processor-front:0.0.1
        ports:
        - containerPort: 3000
        env:
        - name: TARGET_HOST
          value: "http://api-gateway"
        - name: SERVER_PORT
          value: "3000"
        volumeMounts:
        - name: static-volume
          mountPath: /app/static/index.html
          subPath: index.html
      volumes:
      - name: static-volume
        hostPath:
          path: ../video-processor-front/static/index.html
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP