apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack
        ports:
        - containerPort: 4566
        env:
        - name: SERVICES
          value: "s3"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: EDGE_PORT
          value: "4566"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: localstack-data
          mountPath: /var/lib/localstack
        - name: init-script
          mountPath: /etc/localstack/init/ready.d/init.sh
          subPath: init.sh
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: localstack-data
        hostPath:
          path: ./localstack/data
      - name: init-script
        hostPath:
          path: ./localstack/init-aws.sh
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
  - protocol: TCP
    port: 4566
    targetPort: 4566
  type: ClusterIP