apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
      - name: uploader
        image: video-processor-uploader:0.0.1
        env:
        - name: SERVER_PORT
          value: "5001"
        - name: GIN_MODE
          value: "release"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: video-processor-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: video-processor-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "us-east-1"
        - name: S3_ENDPOINT
          value: "http://localstack:4566"
        - name: S3_BUCKET_NAME
          value: "video-bucket"
        - name: S3_USER
          valueFrom:
            secretKeyRef:
              name: video-processor-secrets
              key: S3_USER
        - name: S3_PASS
          valueFrom:
            secretKeyRef:
              name: video-processor-secrets
              key: S3_PASS
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "processor.video.file"
---
apiVersion: v1
kind: Service
metadata:
  name: uploader
spec:
  selector:
    app: uploader
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP